services:
  my_movies_client:
    build:
      context: ./client
      dockerfile: Dockerfile.client
    env_file:
      - path: ./client/.env
    ports:
      - "3000:3000"   
    depends_on:
      - db
  my_movies_server:
    build:
      context: ./server
      dockerfile: Dockerfile.server
    env_file:
      - path: ./server/.env
    ports:
      - "8000:8000"   
    depends_on:
      - db
  db:
    volumes:
      - my_movies:/data/db
    image: mongo:latest
    ports:
      - "27017:27017" 
volumes:
   my_movies: