name: Perform Test & Deploy to Client (Render)
on:
  push:
    branches:
      - main
    paths:
      - client/**
      - .github/workflows/deployment-client.yml
jobs:
  test-client:
    runs-on: ubuntu-latest
    steps:
      - name: Get Code
        uses: actions/checkout@v4
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
      - name: Cypress Run
        uses: cypress-io/github-action@v6
        with:
          working-directory: client
          start: npm start
  deploy-client:
    runs-on: ubuntu-latest
    needs: test-client
    steps:
      - name: Get Code
        uses: actions/checkout@v4
      - uses: johnbeynon/render-deploy-action@v0.0.8
        with:
          service-id: ${{ secrets.RENDER_CLIENT_SERVICE_ID }}
          api-key: ${{ secrets.RENDER_API_KEY }}
