name: Perform Test & Deploy to Client
on:
  push:
    branches:
      - main
    paths:
      - client/**
      - .github/workflows/deployment-client.yml
jobs:
  test-client:
    runs-on: ubuntu-latest
    env:
      REACT_APP_BACKEND_URL: ${{ secrets.REACT_APP_BACKEND_URL }}
    steps:
      - name: Get Code
        uses: actions/checkout@v4
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
      - name: Cypress Run
        uses: cypress-io/github-action@v6
        with:
          working-directory: client
          start: npm start
  deploy-client:
    runs-on: ubuntu-latest
    needs: test-client
    steps:
      - name: Get Code
        uses: actions/checkout@v4
      - name: Deploy
        env:
          deploy_url: ${{ secrets.RENDER_CLIENT_DEPLOY_HOOK_URL }}
        run: |
          curl "$deploy_url"
